// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication6.Models;

namespace WebApplication6.Migrations
{
    [DbContext(typeof(CarDbContext))]
    partial class CarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication6.Models.Car", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvtoTəchizatı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BanNövü")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Barter")
                        .HasColumnType("bit");

                    b.Property<string>("Bazar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElanQüvvəti")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Kredit")
                        .HasColumnType("bit");

                    b.Property<string>("Marka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasinSahibiSayi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MühGücü")
                        .HasColumnType("int");

                    b.Property<int>("MühHəcmi")
                        .HasColumnType("int");

                    b.Property<string>("OlcuVahidi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Premium")
                        .HasColumnType("bit");

                    b.Property<string>("PulVahidi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qiymet")
                        .HasColumnType("int");

                    b.Property<string>("Rəng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SürətlərQutusu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VinKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Vip")
                        .HasColumnType("bit");

                    b.Property<string>("Vəziyəti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YanacağNövü")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yerlerinsayi")
                        .HasColumnType("int");

                    b.Property<float>("Yürüş")
                        .HasColumnType("real");

                    b.Property<string>("Ötürücü")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("İl")
                        .HasColumnType("int");

                    b.Property<string>("Şəhər")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ƏlavəMəlumat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
